config/routes.rb
Rails.application.routes.draw do
  require 'commontator' 
  resources :lectures do
    member do
      get '/lectures/:id/like', to: 'lectures#like', as: 'like'
      get '/lectures/:id/unlikev', to: 'lectures#unlike', as: 'unlike'
    end
  end
  resources :courses
  mount Commontator::Engine => "/commontator"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    belongs_to :user
    has_many :lectures
  def user=(new_user)
    self.old_user = self.user
    super
  end

end

app/models/lecture.rb
class Lecture < ApplicationRecord
    belongs_to :course
    has_and_belongs_to_many :users
    acts_as_commontable
    mount_uploader :attachement, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         enum gender: {male: 0, female: 1} 
         has_many :courses
         has_and_belongs_to_many :lectures
         acts_as_commontator
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :date_of_birth, :gender, :profile_picture])
  end
end

app/controllers/courses_controller.rb
class CoursesController < InheritedResources::Base

  private

    def course_params
      params.require(:course).permit(:title, :user_id)
    end
end

app/controllers/lectures_controller.rb
class LecturesController < InheritedResources::Base
  before_action :set_lecture, :set_user , only: [:like, :unlike]

  def like
    @user.lectures << @lecture
    @user.save
    respond_to do |format|
      format.html { redirect_to "/lectures/#{params[:id]}", notice: 'Lecture was successfully liked' }
    end
  end
  def unlike
    @user.lectures.delete(Lecture.find(@lecture.id))
    respond_to do |format|
      format.html { redirect_to "/lectures/#{params[:id]}", notice: 'Lecture was successfully un liked' }
    end
  end

  private

    def lecture_params
      params.require(:lecture).permit(:content, :attachement, :course_id, :user_id)
    end
    def set_user
      @user = current_user
    end
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :course_title %>
  </div>

  <div class="field">
  <%= form.label :user_id %>
  <%= form.select :user_id, options_for_select(User.all.map{|s|[s.name, s.id]}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>
<p>
  <strong>Course_Creator:</strong>
  <%= @course.user.name %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lectures/_form.html.erb
<%= form_with(model: lecture, :html=>{:multipart=>true}) do |form| %>
  <% if lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :lecture_content %>
  </div>

  <div class="field">
    <%= form.label :attachement %>
    <%= form.file_field :attachement%>
  </div>

  <div class="field">
  <%= form.label :course_id %>
  <%= form.select :course_id, options_for_select(Course.all.map{|s|[s.title, s.id]}) %>
  </div>

  <div class="field">
  <%= form.hidden_field :user_id, value: current_user.id %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lectures</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= lecture.content %></td>
        <td><%= link_to 'Show', lecture %></td>
        <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lecture', new_lecture_path %>

app/views/lectures/new.html.erb
<h1>New Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Back', lectures_path %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @lecture.content %>
</p>

<p>
  <strong>Attachement:</strong>
  <%= @lecture.attachement %>
</p>
<% if(current_user.lectures.include?(@lecture))%>
<td><%= link_to 'unlike', unlike_lecture_url(@lecture) %></td>
<% else %>
<td><%= link_to 'like', like_lecture_url(@lecture) %></td>
<% end %>
<br/>
<br/>
<p>
  <strong>Likes</strong>
  <% @lecture.users.each do |user| %>
 <li><%= user.name %></li>
  <%  end %>
</p>
<br/>
<br/>

<div id="thread_1_div" class="thread" >
      <a data-remote="true" href="/commontator/threads/1">Show Comments </a>
</div>

<br/>
<br/>
<%= link_to 'Edit', edit_lecture_path(@lecture) %> |
<%= link_to 'Back', lectures_path %>